### ISSUE TITLE
Support for LAZ files with wave packets

### ISSUE THREAD

**Issue by Mortano** [laz-rs/laz-rs#21]
From what I can tell, there is no support in `laz-rs` for LAZ files with wave packet data at the moment. Trying to load a such a file fails with `Item with type code: 9 is unknown`. What would it take to add support for wave packet data?

**Comment by tmontaigu** [comment]
To add support for wavepackets the compressor and decompressor it have to be implemented

Id did not add support for wavepacket  because it's impossible to find some example las/laz with wavepackets
