### ISSUE TITLE
Add Records back to public API

### ISSUE THREAD

**Issue by CCInc** [laz-rs/laz-rs#25]
Hi,

For my usage I only want to use the compressor as a means of compressing points I construct externally, similar to here:

https://github.com/laz-rs/laz-rs/blob/b616109ddef63c97a4ffe560de7fea999a5d326c/src/test.rs#L19-L46

I wonder if we can add the `LayeredPointRecordCompressor` and `SequentialPointRecordCompressor` back to the API.

**Comment by CCInc** [comment]
In the meantime I will just use the "benchmarks" feature.

**Comment by tmontaigu** [comment]
I'm not necessarily against it, but I'm curious about what you are doing to be needing the RecordCompressors and not the LasZipCompressor

**Comment by CCInc** [comment]
In my case, I will have multiple input chunks that I generate across multiple threads, and I need the chunks to be maintained in the compression (i.e. each input chunk maps to a compressed chunk). Each thread will compress its own chunk, then write it out to the laz file.

It seems like `ParLasZipCompressor` does a similar thing but it uses threads internally, rather than being thread-safe to call `compress_many` from multiple threads.

What would be most ideal is if I can compress the chunks in their own threads and push them to a stack, then have a single writer process that reads those compressed chunks from the stack and add them to the file. Is there a way to handle this within laz-rs (creating a compressed file structure which handles chunk table, but doesn't actually compress the bytes)? I'm thinking I may have to create it myself.

**Comment by CCInc** [comment]
It looks like what I will have to do is:

1. Create the file and its headers using laszip
2. Create the laszip VLR using laz-rs and write it to the file
2. Compress each chunk on its own thread using RecordCompressor, then add the compressed bytes to the writer queue 
3. The writer thread pulls the compressed chunks from the queue and writes those bytes to the file (starting from `offset_to_points`) using a binary writer
4. At the end, create a chunk table similar to `write_chunk_table`

Does that seem right?

The only thing I'm confused about is how the `chunk_size` for the LazVlr works when using dynamically sized chunks. What does this value in the VLR do?

**Comment by tmontaigu** [comment]
For Parallelized compression and decompression `laz-rz` already provides structs and function:
https://docs.rs/laz/0.5.2/laz/#parallelism

Variable sized chunk are not supported yet tho, I never encountered any

**Comment by CCInc** [comment]
I have not seen any either but I'm working off a new spec which requires variable chunk sizes (https://github.com/copcio/copcio.github.io/blob/main/DRAFT-SPEC.md), so I think the parallel writer would not work out of the box unfortunately.

**Comment by tmontaigu** [comment]
Oh that's interesting

For the compression, the missing part is the variable chunk size support.

For now I think i'll just see how the spec evolves to see what kind of API would be needed

**Comment by CCInc** [comment]
Sounds good. I will use the "benchmark" feature for now. Maybe we could move the records into a feature with a different name that isn't loaded by default.
