### ISSUE TITLE
Conda build

### ISSUE THREAD

**Issue by CCInc** [laz-rs/laz-rs#29]
Hi @tmontaigu ,

I was wondering your thoughts on creating a conda package that combines laz-rs and laz-rs-c. This way, both python and c++ users can simply install the conda package and have access to the headers, python lib, and system lib, and thus allowing them to avoid interacting with rust at all. I'm happy to help create it if you think it's a good idea.

**Comment by tmontaigu** [comment]
closing as a conda package exists
