### ISSUE TITLE
M1 build?

### ISSUE THREAD

**Issue by fabiopicchi** [laz-rs/laz-rs#32]
Hi! Since I migrated to an m1, I can't install laz-rs nor laszip from `pip` (not much interested in laszip, but I would want at least one easily installable laspy backend). I am usually just a python library user so I don't know how libraries get published to pip and how they're tagged and all but it seems that there is no build specifically targeting ARM.

I would be happy to help but, as I said above, I'm not familiar with the stack so it would be great if the maintainer could offer me some quick guidance. Also, I saw some other threads about `conda` support and I'm not sure if this is in place already (couldn't find it from the documentation).

**Comment by fabiopicchi** [comment]
Never mind, further digging enlightened me and I figured out laz-rs-python was the repo I was looking for.
It was quite easy to build and install locally the library with `maturin`.

**Comment by tmontaigu** [comment]
I've been wanting to upload a ARM wheel for macOs on Pypi but havent had the time yet, maybe i'll be able to do it this week end
