### ISSUE TITLE
Wrapping Ops?

### ISSUE THREAD

**Issue by abellgithub** [laz-rs/laz-rs#33]
Hi,

I see that a bunch of operations from the C/C++ implementation have been replaced with Rust's wrapping_add/mul/sub. This seems a good thing to me, since there are overflows/underflows that occur during compression/decompression that *seem* to expect this behavior. I expect that this is what happens in C++, even if it is technically undefined behavior. Anyway, I was just wondering about how this code was tested and how/where you decided to replace raw operations from the laszip code with the wrapping operations in Rust.

Thanks,

**Comment by tmontaigu** [comment]
Hello,

If I'm correct, in C/C++ unsigned overflow is a defined behaviour as wrap around, only overflows on signed integers is undefined.
In Rust I don't know if they consider signed overflow undefined.

As for how I decided to replace some operation with the equivalent `wrapping_*`, it is actually simple: In debug build, cargo/rust enable overflow checks on integer operation, so I just ran my `check` test on my data set in debug build, and the code would crash when an overflow occured, and then I simply changed the line that caused the overflow with a `wrapping_*` and restarted the test to encounter the next overflow error.

**Comment by abellgithub** [comment]
Thanks. This is what I suspected. I should probably clean up the undefined behavior in lazperf where there are overflows like:

```
int a, b;
int i = a + b;
```
And just go with the assumption that the original author assumed that wrapping is what would happen.
