### ISSUE TITLE
Relicence according to LASzip

### ISSUE THREAD

**Issue by pka** [laz-rs/laz-rs#35]
LASzip has been relicenced to Apache Public License 2.0: https://github.com/LASzip/LASzip/commit/8d82288effd827ee90bcb2f1f24cb3cc49026f5c
Maybe laz-rs could also be relicenced to a common Rust license?

**Comment by tmontaigu** [comment]
I saw the change of license for laszip, and wanted to do the same for laz-rs however, i had to some questions
like can I just re license, or do I need explicit agreement from the few other contributors

**Comment by pka** [comment]
You're right, contributors should agree to a new licence. Found this example for a proper relicensing handling: https://github.com/bevyengine/bevy/issues/2373

**Comment by tmontaigu** [comment]
In the bevy example I see that they make a distinction between changes that would require agreement ans the ones that do not (like typo fixes)

I'll look at the contributions and try to contact accordingly

**Comment by tmontaigu** [comment]
I should also actually read the full apache license
