### ISSUE TITLE
Streaming friendly constructor

### ISSUE THREAD

**Issue by ssfabiopicchi** [laz-rs/laz-rs#39]
Currently the `ParLasZipDecompressor` is reading the chunk table on instantiation https://github.com/laz-rs/laz-rs/blob/56e64d00f8e285d95d26d79530c4cddd86dbeae5/src/laszip/parallel/decompression.rs#L47

As a side effect, when you do:
```
with laspy.open(lazfile) as las:
    print(las.header.point_count)
```

The code will read the chunk table without ever using it. That is fine for local files, but in my case we're streaming data from s3 so I resorted to LasHeader.from_source to avoid that. It would be nice, though, if it was possible to use the same friendly API both when I need to read just the headers and when I need to access the points.

If you think this is a good idea, I volunteer to do the update even if I'm not proficient with Rust. I would guess this is a simple change.

**Comment by tmontaigu** [comment]
To me, nothing needs to be modified in laz-rs, its in laspy that something has to be changed

**Comment by ssfabiopicchi** [comment]
Makes sense @tmontaigu. I'll propose a tweak there for the lazy initialization of the decompressor.
