### ISSUE TITLE
`LasZipDecompressor::seek` is broken when seeking into last LAZ chunk for extended point formats

### ISSUE THREAD

**Issue by Mortano** [laz-rs/laz-rs#46]
Hi there! I encountered an issue when trying to use the `LasZipDecompressor::seek` method for LAZ files with point records of format 6 or higher. When I seek into the last chunk of the LAZ file and then read some points, it appears that the decompressor only skips the first point of the chunk and then reads from there, even if I specify a larger offset for `seek`. I uploaded an example that demonstrates this [here](https://github.com/Mortano/laz-rs-seek-issue) (just `cargo run`, the code should be pretty self-explanatory).

I couldn't figure out the exact cause of this myself, but I narrowed it down to [this loop here](https://github.com/laz-rs/laz-rs/blob/aeedab24546dc623e7e31c5632f369a3cf3d578f/src/laszip/decompression.rs#L225), where instead of reading the correct number of points, the decompressor reports being at the end of the chunk after decompressing the first point. Maybe this is helpful?

**Comment by tmontaigu** [comment]
There was indeed a problem, thanks for the example
