### ISSUE TITLE
Invalid cloud written using laspy

### ISSUE THREAD

**Issue by rdesparbes** [laz-rs/laz-rs#51]
## Description

When using the *lazrs* backend with *laspy* to write the attached point cloud, the resulting LAZ file is corrupted.

The attached point cloud has the following characteristics:

- LAS Specification: 1.4
- Point Data Record Format: 8
- Point count: 50 000

## Environment

- Python: 3.8
- OS: Windows

### Python dependencies

- *lazrs*: 0.6.0
- *laspy*: 2.5.4
- *laszip*: 0.2.3

## Steps to reproduce

Copy the following script in a file named `test_corrupted.py`:

```python
from io import BytesIO

import laspy
import pytest

CLOUD_PATH = "corruptible.laz"


@pytest.mark.parametrize(
    "backend",
    [laspy.LazBackend.Laszip, laspy.LazBackend.Lazrs, laspy.LazBackend.LazrsParallel],
)
def test_write_read_corruptible_correctly_loads_cloud(
    backend: laspy.LazBackend,
) -> None:
    cloud = laspy.read(CLOUD_PATH, laz_backend=backend)
    stream = BytesIO()
    with laspy.open(
        stream, mode="w", header=cloud.header, closefd=False, laz_backend=backend
    ) as writer:
        writer.write_points(cloud.points)
    stream.seek(0)
    laspy.read(stream, laz_backend=backend)
```

Download the LAZ file [corruptible.log](https://github.com/user-attachments/files/16284168/corruptible.log) in the same directory as the script and rename it to `corruptible.laz` (*GitHub* would not accept the .laz extension...)

Launch:

```console
pytest test_corrupted.py
```

## Expected result

The 3 tests pass.

## Actual result

The tests related to *lazrs* fail with the following error:

```
self = <laspy._compression.lazrsbackend.LazrsPointReader object at 0x0000019575A1AA90>, n = 50000

    def read_n_points(self, n: int) -> bytearray:
        point_bytes = bytearray(n * self.vlr.item_size())
>       self.decompressor.decompress_many(point_bytes)
E       lazrs.LazrsError: IoError: failed to fill whole buffer

..\Miniconda3\envs\psanp\lib\site-packages\laspy\_compression\lazrsbackend.py:95: LazrsError
```

**Comment by tmontaigu** [comment]
I confirm there is a problem, I found a first bug and its fix, but its not sufficient yet to completely fix

**Comment by tmontaigu** [comment]
lazrs 0.6.1 has been published and should fix the issue
